CATEGORIES = ["Rings", "Necklaces", "Earrings", "Bracelets", "Bangles",
              "Pendants", "Anklets", "Sets"]

BANNERS = [
    {"title": "New Gold Collection", "subtitle": "Pure 22K BIS Hallmarked Gold", "cta": "Shop Now"},
    {"title": "Diamond Sale",        "subtitle": "Up to 40% off certified diamonds", "cta": "Explore"},
    {"title": "Silver Essentials",   "subtitle": "925 Sterling Silver – starting ₹999", "cta": "Discover"},
]

# ── Per-product image URLs provided by user ───────────────────────────────────
IMG = {
    # Named exactly after the product they match
    "eternal_solitaire_ring":   "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYqzeKLYbAWI9lUkmxi8iomUr5jaPvmCChUUfARSb_11AReivDlHVQjbFz2PvceCT82dBn65W4AYR0UkQ436YMRr9t9EB9KgYfaxkjdlgAqbWfBmvwXE4RnDgiM3OpOzb8jG3J0A&usqp=CAc",
    "lotus_temple_ring":        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxr6GsL0rS9LXlWu8eH3PLuoy3Bcbu1oYfYja3cVuB2Q&s=10",
    "rani_haar_necklace":       "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRss-HkMXamxlUygDYz3hZm1qqOYCSZsiqqimmP9trUYcSKmWng_A_sJs4_1XQGIk6oPL96rNq4uPlFHAKtmdatwT7HdJqrID8B4d84spXgW33fGd6mBPnwZRa_8Ri3vJXGvQcTtr0&usqp=CAc",
    "diamond_tennis_necklace":  "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRC4pTT6fsSf4tO08XVxe12fWCJzRDkfEEsn5OGoep5VQ58WuucQnYcqmWoFREwsVtX8uL_0RO7aybLdDzYdCCsJ9OIz_WgAAwOknTAdupeE61idckcWvYXGEl0TKfL0pqOecXftw&usqp=CAc",
    "kundan_choker_set":        "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTvKFzOcW4BPzGtBQCh59WuTNPKXXHZ2Gm1UP8aHtoVKGO5bx70g4BkStfO_0P-b3ug44J5_zIIA-P8H31x_lD2zAbRCut6Mp0hKnZTcKT4QosF3jLwK1zyvc-drdx9y4ShgkCVmJL2KXw&usqp=CAc",
    "jhumka_classic_gold":      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRR5oT7NJHJ2N7W9YBcx0rAxRMeIIPhj0rsU3gIRxve-Edq9-eeJSD3ox7ZQRWP8bUPG78Cn87FXJGG9gzwTmyukFdRFShkJzvDbekxB4ngBxFIYXAsSU76tFtpZOjQ2MKwM8JCvGc&usqp=CAc",
    "meenakari_chandbali":      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSeSadMi70Vilyfbdy70-JEo-VEBw7BcIm21AHPtIzimonNOn5quao844yM5zz-H_JmZok8S3At-qr-eqLFy426SLkolK4q-aYUvpbqe8omGnOVuG6EDfNDjA-hLtGqKyDkSS1vv3k&usqp=CAc",
    "gold_charm_bracelet":      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR4lsTFKd0CRLfPHZodPxMzCUXHelzYG2qdWV46TFjNTuBHQQ8WeCnvFQOVqB0ICOXJ1TbKL4DHRPhnTHz1sFL-Wak6bNwcWErzx1o_6ODq3DZMbiTnjBI6bq4F7vnWH0T2DbEn1w&usqp=CAc",
    # Remaining products keep previous good URLs
    "fallback_1": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTG207I3Fx8VzXoqFg_PZ_QK2yyCGxBb5pKpdfJCr50mgrEOTJJHrMIPUUV3XEguNFD-UiMd9bRMVOkh8P90NOlrVeP8XM3NQZAXsGOQ6Pi-CTbxalaas9gDujdSg73RtdOEqsol9A&usqp=CAc",
    "fallback_2": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSvXcwA0JJLXU8Tzq5HV119UP7h9_xitWJzdCs_U0ysvS66q8qNFGeHCrekDds9aHv9z7DsNzeQQOt_UBDjc44EiZ8YFi9PTOCO1UDt-RNRXPqHevDY36B8XXF-H7GWYn5x6cEwcVY&usqp=CAc",
    "fallback_3": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQQHSRHSKufiz2hJf_pkHPm6iNKw4TgoRKsnDJnnDLxiM158tFAQV4gy78v0Ct2RufxQGd2EBdIRZr-owgFU4DpXlt4IRKZscTNZ6tdvcyJdmcT_WJFW17HXHgK0G_d635mN-HJayRk&usqp=CAc",
    "fallback_4": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRf3a-osSBgYWth_x_cl6MDrOvP8rN3SEXHv_MMMM9W_LuqPLfGKnJZM-9T0_jWj-nrGX3eVRTgfrepZe_66z4ZTcvDlZdEJH3XYpp8jk_CXJYAnW2OB4IPSZ3QtzPUvFvW6ayJ1mU&usqp=CAc",
    "fallback_5": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSr5oC1OYNmGXItfMkgomZbM3W7wC8rM5JfbQxdkSNwQC3gj2XpN8PSo8-0Mdz102Wh2L0L3gnX2KJWJ7TsFmm5W0VOwwkV0QifK7r5sQbL-w81aZHswinDgFvrRU6YgMBbx4mn9Dap&usqp=CAc",
}

PRODUCTS = [
    # ── RINGS ──────────────────────────────────────────────────────────────────
    {
        "id": "r001", "name": "Eternal Solitaire Ring",
        "category": "Rings", "material": "Diamond · 18K Gold",
        "price": 45999, "mrp": 65000, "rating": 4.8, "reviews": 312,
        "emoji": "💍", "new": False, "featured": True,
        "image": IMG["eternal_solitaire_ring"],
        "weight": "3.2g", "purity": "18K Gold (75%)",
        "occasion": "Engagement, Anniversary",
        "description": "A timeless solitaire set in 18K gold, featuring a GIA-certified round brilliant diamond. Crafted for the moment that lasts forever.",
    },
    {
        "id": "r002", "name": "Lotus Temple Ring",
        "category": "Rings", "material": "22K Gold",
        "price": 18500, "mrp": 22000, "rating": 4.6, "reviews": 198,
        "emoji": "🌸", "new": True, "featured": True,
        "image": IMG["lotus_temple_ring"],
        "weight": "4.8g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Traditional",
        "description": "An intricate lotus motif ring in 22K BIS hallmarked gold — rooted in tradition, designed for the modern bride.",
    },
    {
        "id": "r003", "name": "Moonlit Rose Gold Band",
        "category": "Rings", "material": "Rose Gold",
        "price": 12999, "mrp": 15500, "rating": 4.5, "reviews": 145,
        "emoji": "🌙", "new": True, "featured": False,
        "image": IMG["fallback_2"],
        "weight": "2.8g", "purity": "18K Rose Gold",
        "occasion": "Casual, Gift",
        "description": "A sleek rose gold band with a delicate moonstone inlay — effortlessly wearable from dawn to dusk.",
    },
    {
        "id": "r004", "name": "Vintage Emerald Ring",
        "category": "Rings", "material": "Silver · Emerald",
        "price": 8999, "mrp": 11000, "rating": 4.7, "reviews": 87,
        "emoji": "💚", "new": False, "featured": False,
        "image": IMG["fallback_4"],
        "weight": "5g", "purity": "925 Sterling Silver",
        "occasion": "Cocktail, Party",
        "description": "Deep Colombian emerald set in oxidised sterling silver. A statement piece with old-world glamour.",
    },
    # ── NECKLACES ──────────────────────────────────────────────────────────────
    {
        "id": "n001", "name": "Rani Haar Gold Necklace",
        "category": "Necklaces", "material": "22K Gold",
        "price": 78500, "mrp": 92000, "rating": 4.9, "reviews": 421,
        "emoji": "📿", "new": False, "featured": True,
        "image": IMG["rani_haar_necklace"],
        "weight": "32g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Bridal",
        "description": "A regal Rani Haar in 22K gold — a symbol of grace and prosperity that has adorned brides for generations.",
    },
    {
        "id": "n002", "name": "Diamond Tennis Necklace",
        "category": "Necklaces", "material": "Diamond · Platinum",
        "price": 125000, "mrp": 160000, "rating": 4.9, "reviews": 68,
        "emoji": "✨", "new": False, "featured": True,
        "image": IMG["diamond_tennis_necklace"],
        "weight": "15g", "purity": "Platinum 950",
        "occasion": "Evening, Gala",
        "description": "Forty-two round-cut IGI certified diamonds set in platinum. The ultimate expression of understated luxury.",
    },
    {
        "id": "n003", "name": "Dainty Pearl Strand",
        "category": "Necklaces", "material": "Silver · Pearl",
        "price": 5999, "mrp": 8000, "rating": 4.4, "reviews": 203,
        "emoji": "🤍", "new": True, "featured": False,
        "image": IMG["fallback_5"],
        "weight": "8g", "purity": "925 Sterling Silver",
        "occasion": "Office, Casual",
        "description": "Freshwater pearls on a delicate silver chain — a timeless piece for everyday elegance.",
    },
    {
        "id": "n004", "name": "Kundan Choker Set",
        "category": "Necklaces", "material": "Kundan · Gold Plated",
        "price": 4999, "mrp": 6500, "rating": 4.6, "reviews": 334,
        "emoji": "🟡", "new": False, "featured": True,
        "image": IMG["kundan_choker_set"],
        "weight": "45g", "purity": "Gold Plated",
        "occasion": "Festive, Wedding",
        "description": "Vibrant Kundan work on a gold-plated base — a celebration of India's finest jewellery craft.",
    },
    # ── EARRINGS ───────────────────────────────────────────────────────────────
    {
        "id": "e001", "name": "Jhumka Classic Gold",
        "category": "Earrings", "material": "22K Gold",
        "price": 15800, "mrp": 18500, "rating": 4.8, "reviews": 567,
        "emoji": "⭕", "new": False, "featured": True,
        "image": IMG["jhumka_classic_gold"],
        "weight": "8.4g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Festive",
        "description": "The timeless jhumka — reimagined with fine filigree in 22K gold. Where heritage meets heirloom.",
    },
    {
        "id": "e002", "name": "Diamond Stud Solitaire",
        "category": "Earrings", "material": "Diamond · 18K Gold",
        "price": 22500, "mrp": 30000, "rating": 4.7, "reviews": 289,
        "emoji": "💫", "new": False, "featured": False,
        "image": IMG["fallback_1"],
        "weight": "1.8g", "purity": "18K White Gold",
        "occasion": "All occasions",
        "description": "0.5ct each, GIA certified diamond studs in 18K white gold — the jewellery wardrobe essential.",
    },
    {
        "id": "e003", "name": "Meenakari Chandbali",
        "category": "Earrings", "material": "Gold Plated · Meenakari",
        "price": 3299, "mrp": 4500, "rating": 4.5, "reviews": 412,
        "emoji": "🌈", "new": True, "featured": True,
        "image": IMG["meenakari_chandbali"],
        "weight": "12g", "purity": "Gold Plated Brass",
        "occasion": "Festive, Ethnic",
        "description": "Hand-painted meenakari chandbali — each piece unique, each colour a story told in enamel.",
    },
    {
        "id": "e004", "name": "Silver Hoop Earrings",
        "category": "Earrings", "material": "Silver",
        "price": 1999, "mrp": 2800, "rating": 4.3, "reviews": 678,
        "emoji": "🔵", "new": False, "featured": False,
        "image": IMG["fallback_3"],
        "weight": "4g", "purity": "925 Sterling Silver",
        "occasion": "Casual, Office",
        "description": "Minimalist 925 silver hoops — designed to go with everything, from Monday meetings to Friday nights.",
    },
    # ── BRACELETS ──────────────────────────────────────────────────────────────
    {
        "id": "b001", "name": "Gold Charm Bracelet",
        "category": "Bracelets", "material": "18K Gold",
        "price": 28000, "mrp": 34000, "rating": 4.6, "reviews": 156,
        "emoji": "💛", "new": False, "featured": True,
        "image": IMG["gold_charm_bracelet"],
        "weight": "7g", "purity": "18K Gold (75%)",
        "occasion": "Gift, Anniversary",
        "description": "A charm bracelet in 18K gold — collect moments, one charm at a time.",
    },
    {
        "id": "b002", "name": "Diamond Tennis Bracelet",
        "category": "Bracelets", "material": "Diamond · White Gold",
        "price": 89000, "mrp": 110000, "rating": 4.9, "reviews": 43,
        "emoji": "💎", "new": False, "featured": False,
        "image": IMG["fallback_5"],
        "weight": "9g", "purity": "18K White Gold",
        "occasion": "Evening, Special",
        "description": "A continuous line of channel-set round diamonds in 18K white gold — effortless luxury on your wrist.",
    },
    {
        "id": "b003", "name": "Boho Silver Cuff",
        "category": "Bracelets", "material": "Silver",
        "price": 2499, "mrp": 3500, "rating": 4.4, "reviews": 290,
        "emoji": "🌿", "new": True, "featured": False,
        "image": IMG["fallback_2"],
        "weight": "18g", "purity": "925 Sterling Silver",
        "occasion": "Casual, Beach",
        "description": "Hammered sterling silver cuff with tribal motif — made for wanderers and free spirits.",
    },
    # ── BANGLES ────────────────────────────────────────────────────────────────
    {
        "id": "bg001", "name": "Antique Gold Bangle Set",
        "category": "Bangles", "material": "22K Gold",
        "price": 52000, "mrp": 62000, "rating": 4.7, "reviews": 234,
        "emoji": "🔮", "new": False, "featured": True,
        "image": IMG["fallback_4"],
        "weight": "24g (set of 4)", "purity": "22K Gold (91.6%)",
        "occasion": "Bridal, Wedding",
        "description": "Set of 4 antique-finish bangles in 22K gold — each bangle tells a story of timeless Indian craftsmanship.",
    },
    {
        "id": "bg002", "name": "Laakh Bangle with Mirror",
        "category": "Bangles", "material": "Laakh · Gold Plated",
        "price": 1599, "mrp": 2200, "rating": 4.3, "reviews": 445,
        "emoji": "🎪", "new": False, "featured": False,
        "image": IMG["fallback_1"],
        "weight": "35g", "purity": "Gold Plated",
        "occasion": "Festive, Traditional",
        "description": "Handcrafted laakh bangles with mirror work — vibrant, bold, and rooted in Rajasthani tradition.",
    },
    # ── PENDANTS ───────────────────────────────────────────────────────────────
    {
        "id": "p001", "name": "Ganesha Gold Pendant",
        "category": "Pendants", "material": "22K Gold",
        "price": 8900, "mrp": 11000, "rating": 4.8, "reviews": 678,
        "emoji": "🌟", "new": False, "featured": True,
        "image": IMG["fallback_3"],
        "weight": "4g", "purity": "22K Gold (91.6%)",
        "occasion": "Religious, Gift",
        "description": "A beautifully detailed Ganesha pendant in 22K gold — a blessing to carry close to your heart.",
    },
    {
        "id": "p002", "name": "Evil Eye Diamond Pendant",
        "category": "Pendants", "material": "Diamond · Silver",
        "price": 6999, "mrp": 9500, "rating": 4.6, "reviews": 523,
        "emoji": "🔵", "new": True, "featured": True,
        "image": IMG["fallback_2"],
        "weight": "2.5g", "purity": "925 Sterling Silver",
        "occasion": "Everyday, Gift",
        "description": "A dainty evil eye pendant set with a centre diamond — for protection and modern-day magic.",
    },
    # ── ANKLETS ────────────────────────────────────────────────────────────────
    {
        "id": "a001", "name": "Traditional Silver Payal",
        "category": "Anklets", "material": "Silver",
        "price": 2899, "mrp": 3800, "rating": 4.5, "reviews": 312,
        "emoji": "🌙", "new": False, "featured": False,
        "image": IMG["fallback_5"],
        "weight": "20g (pair)", "purity": "925 Sterling Silver",
        "occasion": "Traditional, Wedding",
        "description": "Classic ghungroo payal in pure silver — the sweet sound of tradition with every step.",
    },
    # ── SETS ───────────────────────────────────────────────────────────────────
    {
        "id": "s001", "name": "Bridal Kundan Set",
        "category": "Sets", "material": "Kundan · Gold Plated",
        "price": 12999, "mrp": 18000, "rating": 4.8, "reviews": 267,
        "emoji": "👑", "new": False, "featured": True,
        "image": IMG["fallback_4"],
        "weight": "120g (full set)", "purity": "Gold Plated",
        "occasion": "Bridal, Wedding",
        "description": "Complete bridal set — necklace, earrings, maang tikka, and bangles in ornate Kundan work.",
    },
    {
        "id": "s002", "name": "Diamond Solitaire Set",
        "category": "Sets", "material": "Diamond · 18K White Gold",
        "price": 185000, "mrp": 220000, "rating": 4.9, "reviews": 34,
        "emoji": "💠", "new": False, "featured": True,
        "image": IMG["fallback_1"],
        "weight": "18g", "purity": "18K White Gold",
        "occasion": "Engagement, Anniversary",
        "description": "Matching solitaire ring, earrings, and pendant in 18K white gold with GIA certified diamonds.",
    },
]
